### ISSUE TITLE
Enhancement : bullet points (list)

### ISSUE THREAD

**Issue by benintech** [androidseb/mapmarker#13]
It would be great if bullet points were supported in an item's description

**Comment by androidseb** [comment]
Thanks for proposing this, I wouldn't do just this one thing alone, and I was already thinking about improving the POI description edits with Rich Text functionality. If I add bullet points to the description of a POI, that's how I would do it. I've created an enhancement issue to track this [here](https://github.com/androidseb/mapmarker/issues/15).

I'll close this issue now since this will be included in the above linked issue.
