### ISSUE TITLE
Allow to set the radius of circle

### ISSUE THREAD

**Issue by sballe73** [androidseb/mapmarker#21]
Add a third option to set the radius not by draging the point on the edge but by setting a field to a fixed amount.
This allows to have a precise amount of size for the circle around POIs.
When this option is activated, the edge point would be disabled or would move automatically if the center of the circle is moved to keep the size steady.

**Comment by androidseb** [comment]
Interesting idea! I might be able to achieve this with a relatively low amount of work - while drawing a circle, you have two buttons:

* one to select the center
* one to select the outside of the circle

I could make a third button to set the radius in meters... I'll look at this more in details at some point, assigning the "improvement" label since this is clear enough to be worked on. Timeline TBD.

**Comment by androidseb** [comment]
Done in 3.8.0_697_beta: you can now specify the radius of a circle by long-pressing the circle outside button while placing a circle.

**Comment by sballe73** [comment]
it works :)

**Comment by androidseb** [comment]
Released with version 3.8.0.
