### ISSUE TITLE
Increase the size limit for KMZ exports in Web (currently fails under 2GB)

### ISSUE THREAD

**Issue by fraiyah** [androidseb/mapmarker#28]
Hi dev

i would like to report some issue regarding this exporting kmz file when i tried to export large kmz file its always get stuck @ 99% this is already and issue in version 3.5 i hope you can fix this bug

thanks

**Comment by fraiyah** [comment]
![IMG_20231013_141528_306.jpg](https://github.com/androidseb/mapmarker/assets/70673625/4c2abbe2-c006-48d0-8584-d22ded62dac3)

**Comment by fraiyah** [comment]
![IMG_20231013_141802_222.jpg](https://github.com/androidseb/mapmarker/assets/70673625/c5afad09-8186-4254-8231-9333d20e56f2)

**Comment by fraiyah** [comment]
this issue on webapp only on android and ios no problem

**Comment by androidseb** [comment]
Although Map Marker appears to work on most browsers, the only officially supported browser is Google Chrome:
https://www.mapmarker.app/help/index.html?device=web#devices_web_Various_browser_issues

Could you try this out on Google Chrome and let me know if you're facing the same issue please?

Looking at the error message, it seems unlikely the browser is the source of the problem, but just to double check...

When it works on your mobile device, how large is the exported KMZ file? And how much RAM do you have on your computer?

**Comment by fraiyah** [comment]
Hi dev

thank you for replying to this issue

I tried to open the map marker on chrome browser and imported the 1.1GB KMZ file and it successfully imported, now the problem is when I'm done editing some fields inside the map marker and tried to export still its stuck at 99 % i tried different browsers but still no success in exporting the file 

kindly see the attached images below thank you.

![image](https://github.com/androidseb/mapmarker/assets/70673625/beaaae92-cd8b-482b-9f1a-e8c17e0991e4)

![image](https://github.com/androidseb/mapmarker/assets/70673625/6fb5608c-20ab-4183-862a-84d1ca8f4e04)

**Comment by fraiyah** [comment]
if you want i send you some of my kmz files to replicate the issue. im happy to help in your project

**Comment by fraiyah** [comment]
![image](https://github.com/androidseb/mapmarker/assets/70673625/96520374-031f-41a8-871b-19074e35df4a)

this show after a certain minutes of exporting the kmz files on google chrome but on other browsers it shows memory full

**Comment by androidseb** [comment]
I'm able to see the problem as well on my machine.

Map Marker for web is implemented differently from mobile: since the browser does not have access to the files, the data is stored in memory while zipping / creating a KMZ archive. That will most likely remain a limitation, but ideally if your computer has enough memory (e.g. 8GB for a 1GB export), the export should still work.

I will look at this and see if I can improve this with reasonable efforts short term. With Map Marker 3.6.0, mobile apps are no longer limited to 4GB, it would be nice if the web version's limit was higher than 1GB.

How much RAM do you have on your computer by the way?

**Comment by fraiyah** [comment]
Hi dev

thank you for looking to this issue here is my current system information 
![image](https://github.com/androidseb/mapmarker/assets/70673625/4b2debab-e12a-4ed1-a7b4-bba943ef18d7)

**Comment by androidseb** [comment]
I believe this specific issue can be fixed so I'll take a shot at it.

I'm planning this fix for the next version for now and hopefully will have a fix for this in the beta soon. If I was wrong and I can't fix it for some reason, I might have to close this and document the limitations in the help center page.

Moving this into the roadmap for now, since the plan is now to fix this unless deemed exceedingly difficult.

**Comment by fraiyah** [comment]
Thank you Seb for the effort hope for the best.

**Comment by androidseb** [comment]
@fraiyah I have published a first implementation supporting large zip files in the web app beta here (3.7.0-beta-641):

https://www.mapmarker.app/webapp_beta/

Could you give it a try and let me know if it works for you please? Make sure you use Google Chrome, Firefox won't work.

**Comment by fraiyah** [comment]
@androidseb  hi I have successfully tested the link provided and yes it works! finally I can export KMZ files, though it takes some time to process importing and exporting but I know this can be optimize to lessen the use of computer memory,  thanks seb for fixing this issue.

**Comment by androidseb** [comment]
Thanks for testing! Yes performance is painfully slow, I'll see if I can fix that as well...

**Comment by androidseb** [comment]
I've reworked the underlying storage system for web in version 3.7.0-beta-642, making the file operations significantly faster (e.g. an import of 2.4GB of data went from 7 minutes to only 40 seconds on my machine). Feel free to test it out and provide feedback.

For some reason, zip files of 4GB or more are still causing issue on Web, but I'll track that improvement as a separate initiative:
https://github.com/androidseb/mapmarker/issues/29
