### ISSUE TITLE
app make beep sound when near to POI during Navigation 

### ISSUE THREAD

**Issue by fieldcam** [androidseb/mapmarker#39]
We have inbuilt navigation on this app. It would be a nice feature that when we would be near to a navigation point, it will make beep sound like a rader, beep sound will beep frequently when we go near it.

**Comment by androidseb** [comment]
Thank you for suggesting this idea, could you explain a little more how you would use this please?

Would you expect the beep frequency to be configurable in distance (e.g. 2 beeps per second if 50-100 meters away, 3 beeps per second if 25-50 meters away, 4 beeps per second if 25-10 meters away, etc.)?

Would you expect this to be configurable per-POI?

**Comment by fieldcam** [comment]
Yes like this

**Comment by androidseb** [comment]
It sounds like what you're asking for is similar to what was requested in this issue: https://github.com/androidseb/mapmarker/issues/27

I've edited that other issue to add "The sound / tone / beep could increase in frequency as we get closer." part.

I've skipped the "configurable per POI" part because it probably doesn't have this much value? And added specs for the multiple beep frequency settings per distance.

Could you review [this other issue](https://github.com/androidseb/mapmarker/issues/27) and confirm everything you need in in there?

That other issue has user-provided context for how the feature will be used, could you explain how you would use this? That way I can add your use case there and ensure I don't lose sight of it if I make further edits to the specs.

**Comment by androidseb** [comment]
There hasn't been any recent activity on this issue, I will now close it to keep the backlog clear of stale issues. Feel free to re-open as needed, thank you.
