### ISSUE TITLE
Exploit content.json in another app

### ISSUE THREAD

**Issue by PaysanBarbare** [androidseb/mapmarker#55]
Hello,
It could be interested to get last content.json file easely to use data in a web app and perhaps an API to modify this file without corruption. It can be done actually using google drive and authentification in a php/js scsript I suppose.
For the moment, I do this (capture.png) with autoit, on a computer with Gdrive installed.
![Capture](https://github.com/androidseb/mapmarker/assets/77626202/8634d6a2-d59c-4025-adde-463bbd929bfb)

**Comment by androidseb** [comment]
Hello, thanks for the suggestion, but I'm not sure I get what you're asking.

Could you clarify the product change / improvement you would like to see added to Map Marker for your use case?

The cloud map format used by Map Marker is not publicly documented, is this what you're asking for? Or are you asking for an SDK to modify Map Marker cloud maps?

**Comment by PaysanBarbare** [comment]
Thank you for your answer.
I want to use Map Marker in my farm to be able to know when I move cows from a place to another for example, or show a list of fences I have to repair, or what I have done on meadows (cut grass, spread slurry, what I do last year...).
For this, I need read and write on content.json file with a web app. It can be done using Google Drive authentification and retrieve last zip file in "Map Marker Places Organizer", but perhaps it could be easiest with for example a "REST" API using JSON to read, write, update, delete data to MapMarker.
But sorry, I think I haven't thought enough yet ; perhaps, I can already do whatever I want.

**Comment by androidseb** [comment]
@PaysanBarbare the cloud sync data format is not documented publicly, but for what you're trying to do, this should work, as long as you're re-saving a zip with valid JSON data...

I do not support this officially, but in case it helps, here are some pointers on how Map Marker cloud sync works, use at your own risks, because accidental operations might result in losing your data, even if you should be safe as long as you don't delete anything:

* A cloud map is stored in a cloud map folder (Google Drive or Dropbox)
* Inside the cloud folder, the index file `mm_workspace_index.json` points to the latest map copy
* A map copy is always under the form of a zip file, containing a single `content.json` file
* Images are uploaded separately as dedicated files into the cloud folder
* Map Marker never deletes any file, the only "edits" allowed are on `mm_workspace_index.json`
* When syncing, a new copy of the map:
    * new images are uploaded if any
    * a new zip file is uploaded
    * the `mm_workspace_index.json` file is overwritten to point to the new zip file
* The zip files are assumed to never be edited / deleted
* When checking for cloud changes, only the `mm_workspace_index.json` is checked, so editing an existing zip file won't work for devices that have already synced the map once (zip files are cached by name and only downloaded once)

The `mm_workspace_index.json` file looks something like this:
```
{
    "workspaceName":"The name of the map to display in-app",
    "dataFileName":"name_of_the_zip_file.zip"
}
```

I hope this helps, but since this is not a product change improvement, I'll close this issue. Please let me know if you have more questions, I'll try to answer them.
