### ISSUE TITLE
[Bugfix] Sync error in web app due to Origin Private File System unsupported method (move) usage

### ISSUE THREAD

**Issue by jdvert1** [androidseb/mapmarker#60]
A sync error occurred. Please try again. Not allowed error. The request is not allowed by the user agent or the platforming the current context. 

This is error response is coming from android mobile and from iPhone using Chrome and Safari browser while using the web version of mapmarker. It is working properly from the app in both android and apple iPhone.  

Maybe something on my end but this is happening on multiple phones and different browsers. 

Thank You
![sync error](https://github.com/androidseb/mapmarker/assets/141925911/0780a828-eb88-4128-8bbc-bba16a828fa4)

**Comment by androidseb** [comment]
Hello, thank you for reporting this. Keep in mind the web version is built primarily for desktop computers.

Are you able to test this on a desktop computer running Google Chrome to see if you're running into the same issue? Thanks.

**Comment by jdvert1** [comment]
Thanks for you response. Yes, on the Google Chrome desktop version it works with no problems. I retested on Google Chrome mobile version on a Samsung S24 and iPhone and it gets a sync error. Also, when you change from mobile to desktop version on your Google Chrome on phone you get same error. I tried on a few other phones same thing. 

It used to work before but something changed? I also have the application which works great. 

Thanks. 😊😊
![map marker error](https://github.com/androidseb/mapmarker/assets/141925911/3004ef51-4165-46a7-bb2c-476a5d86f5cd)

**Comment by androidseb** [comment]
The web app is not really meant to be used on mobile, but I don't see a reason why it wouldn't work at the moment, so I'll look into this and see if I can fix it still.

I thought this might be due to using the [origin private file system](https://developer.mozilla.org/en-US/docs/Web/API/File_System_API/Origin_private_file_system) I introduced in 3.7.0 to boost file performance in Web, but that might not be the actual issue, since this seems to be supported even on mobile browsers on paper.

I can't promise I'll actually fix this, but I'll at least take a look to understand where this issue is coming from, I'm getting the same errors from my mobile when testing this.

**Comment by androidseb** [comment]
So I dug into this a little more and I think I found the source of the problem...

My code was using the [origin private file system](https://developer.mozilla.org/en-US/docs/Web/API/File_System_API/Origin_private_file_system)'s `FileSystemFileHandle.move` method which is not supported in Google Chrome officially: https://developer.mozilla.org/en-US/docs/Web/API/FileSystemHandle#browser_compatibility

In practice however, it seems like this method is actually (unofficially) supported on desktop versions of Google Chrome (I have version 124 but I don't know since when this is supported), which is why I didn't catch this issue because my browser testing is limited to Google Chrome desktop. The [documentation](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemHandle#browser_compatibility) clearly says this for the `FileSystemFileHandle.move` method:

> Non-standard. Expect poor cross-browser support.

On mobile (Google Chrome included) it seems `FileSystemFileHandle.move` is not supported at all which causes this "NotAllowedError" you encountered @jdvert1.

I have published version `3.8.0-beta-705` of the Map Marker Web App beta here: https://www.mapmarker.app/webapp_beta/

This issue should be fixed there, please test it out and let me know if you can confirm the fix, thank you.

**Comment by jdvert1** [comment]
Thank you very much for your detailed explanation and for diving into the
issue further.

I truly appreciate the effort you've put into investigating and addressing
the problem.

I understand that dealing with the technical aspects of browser
compatibility can be challenging, especially with unofficially supported
methods like FileSystemFileHandle.move and probably other system and data
issues.

Your diligence in identifying the source of the problem and promptly
releasing version 3.8.0-beta-705 of the Map Marker Web App is commendable.

I just tested out the beta version for bringing up the markers(POI) and
data and it appears that it working as it did before.

Once again, thank you for your dedication to improving the functionality of
the app.

Best regards,

JD

**Comment by androidseb** [comment]
Released with version 3.8.0.
