### ISSUE TITLE
cannot open map on webapp, sync issue

### ISSUE THREAD

**Issue by sballe73** [androidseb/mapmarker#67]
Cannot use anymore a map out of the phone, I get this error on webapp.
![image](https://github.com/androidseb/mapmarker/assets/8128986/f3013729-c1cb-4dc3-9232-047308c7d5fc)
I can still open it from the phone, but I cannot from webapp.

**Comment by androidseb** [comment]
Hello, thank you for reporting this.

The web app is meant primarily for desktop computers running Google Chrome, so there might be some issues on mobile browsers where features are more limited... What browser are you using from your mobile device?

**Comment by sballe73** [comment]
I rephrase, I used Firefox and chrome on PC Linux. 
It used to work, I think it broke after a test on the same map from beta version a while ago. 
I shared you the map by mail.
I can still consult and use from the android app but not anymore this map from PC.

**Comment by androidseb** [comment]
It is expected that this isn't working on Firefox because the "remove" method of the File System API is not supported currently:
https://developer.mozilla.org/en-US/docs/Web/API/FileSystemHandle/remove

However this should be working on Google Chrome regardless of the operating system. I use Google Chrome on Linux as well and I haven't been able to reproduce this issue. Could you please confirm that you get this exact same error on Google Chrome as well? I get this error on Firefox, not Chrome.

**Comment by sballe73** [comment]
indeed it works on chrome...

sorry to have bothered.
