### ISSUE TITLE
sharing maps

### ISSUE THREAD

**Issue by sballe73** [androidseb/mapmarker#68]
I have a full version and I want to share a map publicly (read only).
I cannot request all people to get a full licence to consult the map.  I do not need cloud sync.

Exports to KML are not very good, you loose a lot of what you prepare in your app. And I would prefer them to use your app to consult the file to get the same interface.

How to share ? Can I save as, so people can download on their phone (that is not cloud sync) ?

**Comment by androidseb** [comment]
Hello,

Currently, without the cloud sync, the best way to achieve that is to export your map as a KMZ file. In that format, the entire map data should be exported, and others can import all the data back in their app from the KMZ file. You could share that KMZ file publicly for easy download, but then users would still need to run the import steps manually to import the KMZ file.

Does this answer your question?

**Comment by sballe73** [comment]
Not really, the kmz export does not open as in your app in any other app. You loose format, colors, ability to have offline background. I tried several others apps to open the kmz without having good result. 
Beside, what is the point using your app if I need others to use another app if I want to share :)
It would be enough to have a file open option/save local on phone.
By the way, where do you store the local files on phone?

**Comment by androidseb** [comment]
Maybe I'm not understanding the entire flow here, when you say "I want to share a map publicly", do you mean you want to share it with other users who also have the app installed? Because this is what I had in mind in my previous question:

* Export your map as KMZ
* Host the KMZ file on a publicly shared link
* Instruct people to download and install Map Marker, download the KMZ file and import it

Or are you suggesting something else where the target users you want to share the map with would not even have Map Marker installed potentially?

**Comment by sballe73** [comment]
Of course it works...
I had assumed that as it is not "save" but "export", it is not to be opened by your own app on another device.
Thanks
